Calendar = 
ADDCOLUMNS(
    CALENDAR(DATE(2024, 12, 1), DATE(2026, 3, 31)),
    "Year", YEAR([Date]),
    "Month", MONTH([Date]),
    "MonthName", FORMAT([Date], "MMMM"),
    "MonthShort", FORMAT([Date], "MMM"),
    "MonthNumber", MONTH([Date]),
    "YearMonth", FORMAT([Date], "YYYY-MM"),
    "YearMonthKey", YEAR([Date]) * 100 + MONTH([Date]),
    "Day", DAY([Date]),
    "Weekday", WEEKDAY([Date], 2),  -- 1=Sunday, 2=Monday
    "WeekdayName", FORMAT([Date], "dddd"),
    "ISOWeekNumber", WEEKNUM([Date], 21),  -- ISO 8601: Week starts Monday
--    "Quarter", "Q" & FORMAT([Date], "Q"),
--    "QuarterNumber", INT((MONTH([Date]) - 1) / 3) + 1,
    
    // Fiscal Year Logic (April–March)
    "FiscalYear", IF(MONTH([Date]) >= 4, YEAR([Date]), YEAR([Date]) - 1),
    "FiscalMonth", IF(MONTH([Date]) >= 4, MONTH([Date]) - 3, MONTH([Date]) + 9),
    "FiscalQuarter", 
        SWITCH(TRUE(),
            MONTH([Date]) IN {4,5,6}, "Q1",
            MONTH([Date]) IN {7,8,9}, "Q2",
            MONTH([Date]) IN {10,11,12}, "Q3",
            MONTH([Date]) IN {1,2,3}, "Q4"
        ),
    "FiscalYearMonthKey", 
        IF(MONTH([Date]) >= 4, 
            YEAR([Date]) * 100 + (MONTH([Date]) - 3), 
            (YEAR([Date]) - 1) * 100 + (MONTH([Date]) + 9)
        ),
    
    // Flags
    "IsWeekend", IF(WEEKDAY([Date], 2) >= 6, TRUE(), FALSE()),
    "IsToday", IF([Date] = TODAY(), TRUE(), FALSE())
)
